services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  rate-limiter-1:
    build: .
    image: rate-limiter-1
    container_name: rate-limiter-1
    depends_on:
      - redis
    ports:
      - "8081:8080"
    environment:
      - REDIS_ADDR=redis:6379

  rate-limiter-2:
    build: .
    image: rate-limiter-2
    container_name: rate-limiter-2
    depends_on:
      - redis
    ports:
      - "8082:8080"
    environment:
      - REDIS_ADDR=redis:6379

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
