services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  rate-limiter:
    build: .
    container_name: rate-limiter
    depends_on:
      - redis
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"